### ISSUE TITLE
problem during "mvn verify"

### ISSUE THREAD

**Issue by mudongliang** [Programming-Systems-Lab/phosphor#13]
Based on the README, you use jdk 1.7.0_45. I  install this version: 
```
$ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /opt/jdk1.7.0_45/jre
...
```
Then I clone this repo and execute "mvn verify" recommended by README. I encounter the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project Phosphor: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
More error logs refer to [Full Log](https://gist.github.com/mudongliang/2ab4dbf467f43b1c863e).

**Comment by jon-bell** [comment]
While you can use Phosphor with Java 7 JRE's, due to some annoyances with building and testing against lambdas, you need to use Java 8 to build Phosphor. I will update the readme to make this clearer: You can use Phopshor to instrument a Java 7 JRE, but you can not run Phosphor's test suite against Java 7, it needs Java 8.
