### ISSUE TITLE
How to get the taint tag of an object?

### ISSUE THREAD

**Issue by BihuanChen** [Programming-Systems-Lab/phosphor#2]
As said in README, "to get or set the taint tag of an object, developers first cast that object to the interface TaintedWithIntTag or TaintedWithObjTag (Phosphor changes all classes to implement this interface), and use the get and set methods."

It is not clear whether to use ((TaintedWithIntTag)object).getPHOSPHOR_TAG() or Tainter.getTaint((TaintedWithIntTag)object). So I tried both.

```java
public class TestVariables {

	public static void test(int x, int y) {						
		Pair p = new Pair(x, y);
		int tag1 = ((TaintedWithIntTag)p).getPHOSPHOR_TAG();
		//int tag2 = Tainter.getTaint((TaintedWithIntTag)p);
		System.out.println((tag1 & 1) + " " + (tag1 & 2));
		//System.out.println((tag2 & 1) + " " + (tag2 & 2));
	}
		
	public static void main(String[] args) {
		int x = Tainter.taintedInt(1, 1);
		int y = Tainter.taintedInt(1, 2);
		test(x, y);
	}
	
}

class Pair {
	
	private int h;
	private int w;
	
	public Pair(int h, int w) {
		this.h = h;
		this.w = w;
	}

	public int getH() {
		return h;
	}

	public void setH(int h) {
		this.h = h;
	}

	public int getW() {
		return w;
	}

	public void setW(int w) {
		this.w = w;
	}
	
}
```

When using ((TaintedWithIntTag)object).getPHOSPHOR_TAG(), java.lang.ArrayIndexOutOfBoundsException is thrown during the instrumentation of this example.

When using Tainter.getTaint((TaintedWithIntTag)object), the output is: 0 0. However, my expected output should be: 1 2.

I also tried to find some examples in the given test cases, but failed. Am I interacting with Phosphor in the wrong way to get the taint tag of an object? Please help to give some examples. Thanks.

**Comment by jon-bell** [comment]
The expected output here is actually 0 0. The tag on p.x and p.y should be 1 and 2 respectively though. I'm not sure why you would want it to be 1 2 - I think that if you had a rule like "when storing tainted data, also taint the owner of that data", it would be very hard to 1: determine all of the things that point to that variable and 2: decide when to stop rolling this up (otherwise you end up tainting all heap roots with every tag?)

The arrayindexoutofbounds was a bug - latest commit is fixed and includes a test case showing the get/set method usage. Either Tainter.getTaint or (TaintedWithIntTag).getPHOSPHOR_TAG should work.

**Comment by BihuanChen** [comment]
Yes, your concern is right. After thinking the problem thoroughly, I think there is actually no need for such a heavy rule. Now the tool works fine. Thank you.
