### ISSUE TITLE
Object Tainting 

### ISSUE THREAD

**Issue by chhokrad** [Programming-Systems-Lab/phosphor#50]
Hi Jon

I am using Phosphor's dynamic taint analysis to find out whether loop variables in a java source code are tainted by user defined sources. As per my understanding, if an object is marked as tainted by the method, MultiTainter.TaintedObject(), does not taint the fields of the object. Is there a way to change this behavior to mark the object as well as all the fields (private and public) contained inside the object.

Thanks
Ajay D Chhokra

PS: I was able to taint the Non primitive type fields by reflection but not able to achieve the same for primitive types.

**Comment by jon-bell** [comment]
Hi Ajay,
Recursively traversing the fields of an object is up to you. This comes up every now and then, and the problem is generally that it's difficult to decide where to limit the depth of the traversal. Eventually you end up at java.* classes (even collections) that share references to one thing, and then you end up exploding and tainting most things. Hence, I do not support this directly in Phosphor (but, given a concrete proposal that is shown to work, I would be open to adding).

You should be able to taint the fields using reflection, even the primitive ones.

field.set(obj,MultiTainter.taintedInt(10,...)) should work. If not, can you please provide a minimum example to show it not working (preferably in the form of a failing JUnit test case that will run with the rest of the regression suite)?

**Comment by chhokrad** [comment]
Hi Please find the zip folder that contains the example. Directory structure is as follows:-
Archive.zip
------TestCaseForPhosphor.jar
------------META-INF
------------------MANIFEST.MF
------------Foo.class
------------Foo.java
------------FieldTaintingTestRunner.class
------------FieldTaintingTestRunner.java
------------MyTainter.class
------------MyTainter.java
------------FieldTaintingTest.class
------------FieldTaintingTest.java
------------Moo.class
------------Moo.java
------TestCaseForPhosphor_lib
------------Phosphor-0.0.3-SNAPSHOT.jar
------------junit.jar
------------org.hamcrest.core_1.3.0.v201303031735.jar


There are three tests out of which 2 fail, both tests check the taint of a primitive field (Foo.x and Moo.flag).
primitiveFieldsShouldbeTainted_1(FieldTaintingTest): flag_ should be tainted
primitiveFieldsShouldbeTainted_2(FieldTaintingTest): x_ should be tainted


[Archive.zip](https://github.com/Programming-Systems-Lab/phosphor/files/1342410/Archive.zip)

**Comment by jon-bell** [comment]
Sorry, I should have been clearer: I was suggesting that you create a fork of Phosphor, and add a test case (to the existing suite of tests, that run with mvn verify). 

I looked over your code but it was not clear to me exactly how I should run it (again, in the future, please make a fork and add a test to the existing suite). Does it work if you use setBoolean, getBoolean, setInt, getInt instead of just set/get?

**Comment by chhokrad** [comment]
Hi Jon, 

Sorry for replying late, I was occupied with some other work. I submitted a pull request with 3 test cases. Could you please let me know if something else is required from my side.

Thanks Ajay

**Comment by jon-bell** [comment]
Uh, kind of. I was suggesting that you add write something of a more minimal test case that was a little clearer (no moo, foo, recursive field lookup etc). For instance, the commit that I just added, cfa11f9ca55c56d5733686282895e15878407a85 shows that, clearly, Phosphor doesn't have a problem tainting primitive fields through reflection.

You had a very simple bug in your code unrelated to Phosphor. This line: `field_.get(field.get(obj)).getClass().isPrimitive()` is guaranteed to always return `false`. You are fetching the value and boxing it into an `Integer`, then looking to see if the value is primitive, and it never can be, because you specifically asked Java to give you an `Integer` and not an `int`.

The correct way to see if a field is primitive is `field.getType().isPrimitive()` (again, this has nothing to do with Phosphor, it's how Java works, try it out without Phosphor and see).
